---
- name: Ensure the system is updated, upgraded, and SSH setup is configured
  hosts: all
  become: true
  tasks:
    - name: Update the package list (apt update)
      apt:
        update_cache: yes

    - name: Upgrade all packages (apt upgrade)
      apt:
        upgrade: dist
        cache_valid_time: 3600

    - name: Remove unnecessary packages (apt autoremove)
      apt:
        autoremove: yes

    - name: Install openssh-server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Enable and start the SSH service
      systemd:
        name: ssh
        enabled: yes
        state: started

    - name: Allow root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin yes"
        state: present

    - name: Restart SSH service to apply changes
      systemd:
        name: ssh
        state: restarted
