---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: true
  tasks:
    # Step 1: Uninstall conflicting packages
    - name: Uninstall old and conflicting Docker packages
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
        purge: yes

    # Step 2: Install prerequisite packages
    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    # Step 3: Add Docker’s official GPG key
    - name: Add Docker's official GPG key
      command: |
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Step 4: Set up the Docker repository
    - name: Add Docker repository to apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        warn: false

    # Step 5: Update apt cache again
    - name: Update apt package index
      apt:
        update_cache: yes

    # Step 6: Install Docker Engine, CLI, and plugins
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
